(function(){
"use strict";
const trains=[
 {id:"EXP-620",type:"voyageurs",route:"Owendo → Franceville",position:"Lopé",load:"642 voyageurs",eta:"07:15",delay:0,status:"À l’heure",speed:72,loco:"CC-2200-04",next:"Booué",cargo:"Bagages 418 · 604 billets contrôlés",team:"Jean Obame · 12 agents",x:45,y:49},
 {id:"OMN-218",type:"voyageurs",route:"Franceville → Owendo",position:"Booué",load:"385 voyageurs",eta:"18:40",delay:18,status:"Retard léger",speed:48,loco:"CC-2200-09",next:"Lopé",cargo:"Bagages 246 · 351 billets contrôlés",team:"Marie Nze · 9 agents",x:58,y:38},
 {id:"MIN-641",type:"minerai",route:"Moanda → Owendo",position:"Lastourville",load:"3 150 t",eta:"16:20",delay:12,status:"Retard léger",speed:56,loco:"CC-2200-17",next:"Booué",cargo:"Manganèse · Comilog · 45 wagons",team:"Serge Obame · 3 agents",x:70,y:27},
 {id:"MIN-642",type:"minerai",route:"Moanda → Owendo",position:"PK 408",load:"2 980 t",eta:"19:05",delay:0,status:"À l’heure",speed:61,loco:"CC-2200-12",next:"Lastourville",cargo:"Minerai enrichi · 42 wagons",team:"Paul Ndong · 3 agents",x:65,y:31},
 {id:"BOIS-204",type:"bois",route:"Ndjolé → Owendo",position:"PK 118",load:"1 180 t",eta:"18:10",delay:0,status:"À l’heure",speed:50,loco:"CC-2200-06",next:"Ntoum",cargo:"Grumes · arrimage contrôlé · 28 wagons",team:"Marc Rombi · 3 agents",x:27,y:69},
 {id:"HC-118",type:"hydrocarbures",route:"Owendo → Franceville",position:"Booué",load:"920 000 L",eta:"05:40",delay:0,status:"Sous surveillance",speed:44,loco:"CC-2200-21",next:"Lastourville",cargo:"Gasoil · étanchéité conforme · 18 citernes",team:"Luc Mbadinga · sécurité",x:56,y:40},
 {id:"FRET-332",type:"fret",route:"Owendo → Franceville",position:"Ndjolé",load:"840 t",eta:"09:20",delay:0,status:"À l’heure",speed:54,loco:"CC-2200-11",next:"Lopé",cargo:"Marchandises diverses · 22 wagons",team:"Diane Moukagni · 4 agents",x:34,y:58},
 {id:"CONT-064",type:"fret",route:"Owendo → Booué",position:"Terminal Owendo",load:"36 conteneurs",eta:"22:10",delay:0,status:"En attente",speed:0,loco:"CC-2200-03",next:"Ntoum",cargo:"36 conteneurs · 19 wagons",team:"Équipe terminal T2",x:13,y:83},
 {id:"MAINT-017",type:"maintenance",route:"Booué → PK 246",position:"PK 231",load:"8 agents",eta:"14:30",delay:0,status:"Intervention",speed:18,loco:"DRAISINE-07",next:"PK 246",cargo:"Inspection voie · ultrasons rail",team:"Luc Mbadinga · 8 agents",x:52,y:43}
];
const labels={voyageurs:"Voyageurs",minerai:"Minerais",bois:"Bois",hydrocarbures:"Hydrocarbures",fret:"Fret général",maintenance:"Maintenance"};
const incidents=[["INC-0821","Majeur","Signalisation","PK 316","MIN-641","13:08","Équipe Voie 2","En traitement"],["INC-0819","Mineur","Retard voyageur","Booué","OMN-218","12:46","Régulation","Surveillance"],["INC-0816","Information","Travaux voie","PK 231","MAINT-017","11:20","Maintenance","Planifié"]];
const stations=[["Owendo","6","840","3 200 t","3/4","Forte activité"],["Ndjolé","3","126","840 t","2/2","Normal"],["Booué","4","218","520 t","1/2","Fonctionnement dégradé"],["Moanda","5","340","7 200 t","3/3","Normal"],["Franceville","4","610","1 260 t","2/3","Normal"]];
const teams=[["Alain Moussavou","Régulateur","Centre de contrôle","06:00–14:00","En poste"],["Jean Obame","Conducteur","EXP-620","17:30–08:00","En mission"],["Diane Moukagni","Cheffe de gare","Booué","07:00–15:00","En poste"],["Luc Mbadinga","Technicien voie","PK 231","08:00–16:00","Intervention"]];
const stock=[["CC-2200-17","Locomotive","MIN-641","En service","Dans 1 250 km"],["CC-2200-08","Locomotive","Dépôt Owendo","Disponible","Dans 4 jours"],["WGC-118","Wagon-citerne","HC-118","En service","Conforme"],["V-PREM-04","Voiture voyageurs","EXP-620","En service","Conforme"]];
let selected="EXP-620",filter="all",view="circulations",search="";
const ico=n=>`<i data-lucide="${n}"></i>`;
const tag=(text,cls="")=>`<span class="op-tag ${cls}"><i></i>${text}</span>`;
function shown(){return trains.filter(t=>{let ok=filter==="all"||filter===t.type||filter==="late"&&t.delay||filter==="incident"&&t.id==="MIN-641";return ok&&(!search||Object.values(t).join(" ").toLowerCase().includes(search))})}
function header(){return `<header class="op-header"><div><h1>Centre des opérations</h1><p>Supervision en temps réel du trafic voyageurs, fret et maintenance</p></div><div class="op-actions"><div class="op-sync"><b>02 août 2026 · <span id="opClock">16:55:00</span></b><span><i></i> Réseau connecté · actualisé il y a <b id="syncAge">8 s</b></span></div><button class="btn ghost" data-op="refresh">${ico("refresh-cw")} Actualiser</button><button class="btn ghost" data-op="incident">${ico("triangle-alert")} Déclarer un incident</button><button class="btn primary" data-op="new">${ico("plus")} Nouvelle opération</button></div></header>`}
function kpis(){let d=[["Trains actifs","18","5 voyageurs · 13 fret","train-front","all"],["Ponctualité","91 %","2 trains en retard","clock-3","late"],["Incidents","4","1 incident majeur","triangle-alert","incident"],["Fret du jour","22 650 t","Objectif : 31 480 t","package-open","fret"],["Voyageurs","1 820","Occupation moyenne : 76 %","users","voyageurs"],["Agents en poste","146","2 équipes disponibles","hard-hat","teams"]];return `<div class="op-kpis">${d.map(x=>`<button data-kpi="${x[4]}"><i>${ico(x[3])}</i><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></button>`).join("")}</div>`}
function tabs(){return `<nav class="op-tabs">${[["circulations","Circulations"],["incidents","Incidents · 4"],["gares","Gares"],["equipes","Équipes"],["ressources","Ressources"]].map(x=>`<button data-view="${x[0]}" class="${view===x[0]?"active":""}">${x[1]}</button>`).join("")}</nav>`}
function filters(){let f=[["all","Tous"],["voyageurs","Voyageurs"],["minerai","Minerais"],["bois","Bois"],["hydrocarbures","Hydrocarbures"],["fret","Fret général"],["maintenance","Maintenance"],["late","En retard"],["incident","Avec incident"]];return `<div class="op-toolbar"><label>${ico("search")}<input id="opSearch" value="${search}" placeholder="Rechercher un train, une locomotive, une gare ou un client"></label><div><button data-op="period">Aujourd’hui</button><button data-op="columns">${ico("columns-3")}</button><button data-op="export">${ico("download")} Exporter</button></div></div><div class="op-filters">${f.map(x=>`<button data-filter="${x[0]}" class="${filter===x[0]?"active":""}">${x[1]}</button>`).join("")}</div>`}
function trainRows(){let a=shown();if(!a.length)return `<tr><td colspan="9"><div class="op-empty">${ico("search-x")}<b>Aucune circulation ne correspond aux filtres sélectionnés.</b></div></td></tr>`;return a.map(t=>`<tr data-train="${t.id}" class="${selected===t.id?"selected":""}"><td><b>${t.id}</b></td><td>${tag(labels[t.type],"type-"+t.type)}</td><td><b>${t.route.split(" → ")[0]}</b><small>→ ${t.route.split(" → ")[1]}</small></td><td>${t.position}</td><td>${t.load}</td><td>${t.eta}</td><td class="${t.delay?"late":"ontime"}">${t.delay?"+"+t.delay+" min":"À l’heure"}</td><td>${tag(t.status,t.delay?"warn":"good")}</td><td><button class="dots-btn" data-op="menu">•••</button></td></tr>`).join("")}
function trainTable(){return `<section class="card op-table-card"><div class="op-title"><div><b>Circulations en temps réel</b><small><i class="live"></i>${shown().length} circulations affichées · mise à jour automatique</small></div></div>${filters()}<div class="op-table-wrap"><table class="op-table"><thead><tr>${["Train","Type","Trajet","Position","Charge","Arrivée","Écart","Statut",""] .map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${trainRows()}</tbody></table></div><footer>1–${shown().length} sur ${shown().length}<span><button>‹</button><button class="active">1</button><button>›</button></span></footer></section>`}
function map(){let st=[["Owendo",12,84],["Ntoum",20,75],["Ndjolé",33,60],["Lopé",45,49],["Booué",58,38],["Lastourville",70,27],["Moanda",79,21],["Franceville",87,15]];return `<section class="card op-map-card"><div class="op-title"><div><b>Carte du réseau</b><small>Transgabonais · positions en direct</small></div><button data-op="fullscreen">${ico("maximize-2")}</button></div><div class="op-map"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M10 88 C22 70 27 67 35 58 S49 46 58 38 S74 25 90 12"/></svg>${st.map(s=>`<span class="station" style="left:${s[1]}%;top:${s[2]}%"><i></i><em>${s[0]}</em></span>`).join("")}${shown().map(t=>`<button data-train="${t.id}" class="marker type-${t.type} ${t.delay?"delay":""} ${selected===t.id?"selected":""}" style="left:${t.x}%;top:${t.y}%"><span>${t.id.split("-")[1]}</span><aside><b>${t.id} · ${labels[t.type]}</b><small>${t.route}</small><small>${t.speed} km/h · ${t.load}</small><small>${t.status}</small></aside></button>`).join("")}<div class="map-tools"><button data-op="zoom">+</button><button data-op="zoom">−</button><button data-op="center">${ico("locate-fixed")}</button></div><div class="map-chips"><button>Tous</button><button>Voyageurs</button><button>Fret</button><button>Incidents</button></div></div></section>`}
function detail(){let t=trains.find(x=>x.id===selected)||trains[0];return `<section class="card op-detail"><header><div><small>${labels[t.type]}</small><h2>${t.id}</h2><p>${t.route}</p></div>${tag(t.status,t.delay?"warn":"good")}</header><div class="vitals">${[["Position",t.position],["Prochaine gare",t.next],["Vitesse",t.speed+" km/h"],["Charge",t.load],["Locomotive",t.loco],["Transmission","Il y a 8 s"]].map(x=>`<div><small>${x[0]}</small><b>${x[1]}</b></div>`).join("")}</div><nav><button class="active">Synthèse</button><button>${t.type==="voyageurs"?"Voitures":"Wagons"}</button><button>${t.type==="voyageurs"?"Voyageurs":"Marchandises"}</button><button>Équipe</button><button>Chronologie</button></nav><div class="summary"><p>${ico("train-front")}<span><small>Composition / mission</small><b>${t.type==="maintenance"?"Inspection de la voie":t.load+" · "+t.loco}</b></span></p><p>${ico("package-check")}<span><small>Chargement / contrôle</small><b>${t.cargo}</b></span></p><p>${ico("users")}<span><small>Équipe affectée</small><b>${t.team}</b></span></p></div><button class="btn ghost full" data-op="detail">Ouvrir la fiche opérationnelle ${ico("arrow-right")}</button></section>`}
function alerts(){return `<section class="card op-alerts"><div class="op-title"><div><b>Alertes et incidents</b><small>Priorités opérationnelles</small></div><button data-view="incidents">Tout voir</button></div><button data-train="MIN-641" class="critical">${ico("radio-tower")}<span><b>Défaut de signalisation · PK 316</b><small>Équipe technique en route · résolution 13:40</small></span><em>Majeur</em></button><button data-train="OMN-218" class="warning">${ico("clock-alert")}<span><b>OMN-218 · retard de 18 min</b><small>Régulation en cours à Booué</small></span><em>12:46</em></button></section>`}
function generic(title,headers,data){return `<section class="card op-generic"><div class="op-title"><div><b>${title}</b><small>Données opérationnelles actualisées</small></div><button data-op="export">${ico("download")} Exporter</button></div><div class="op-table-wrap"><table class="op-table"><thead><tr>${headers.concat([""]).map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${data.map(r=>`<tr>${r.map((x,i)=>`<td>${i?x:`<b>${x}</b>`}</td>`).join("")}<td><button class="dots-btn" data-op="menu">•••</button></td></tr>`).join("")}</tbody></table></div></section>`}
function body(){if(view==="circulations")return `<div class="op-main"><div>${trainTable()}</div><aside>${map()}${detail()}${alerts()}</aside></div>`;if(view==="incidents")return generic("Incidents ouverts",["Référence","Gravité","Catégorie","Localisation","Train","Heure","Responsable","Statut"],incidents);if(view==="gares")return generic("Suivi des gares",["Gare","Trains attendus","Voyageurs","Fret","Quais","Statut"],stations);if(view==="equipes")return generic("Agents et équipes en service",["Agent","Fonction","Affectation","Service","Statut"],teams);return `<div class="resource-kpis">${[["12","Locomotives disponibles"],["18","En circulation"],["4","En maintenance"],["2","Immobilisées"]].map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join("")}</div>`+generic("Ressources et matériel",["Matériel","Type","Affectation","État","Maintenance"],stock)}
function render(){let root=document.querySelector("#content");if(!root)return;root.innerHTML=header()+`<button class="op-banner" data-op="network"><span>${ico("circle-check-big")} <b>Réseau opérationnel à 99,4 %</b></span><span>18 trains actifs</span><span>2 retards</span><span>1 incident majeur</span><span>Aucune interruption complète</span>${ico("chevron-right")}</button>`+kpis()+tabs()+`<div id="opBody">${body()}</div>`;if(window.lucide)lucide.createIcons()}
function redraw(){let b=document.querySelector("#opBody");if(b){b.innerHTML=body();if(window.lucide)lucide.createIcons()}}
pages.tracking=function(){setTimeout(render,0);return `<div class="op-loading"><i></i><i></i><i></i></div>`};
document.addEventListener("click",e=>{if(!document.querySelector(".op-header"))return;let v=e.target.closest("[data-view]");if(v){view=v.dataset.view;render();return}let f=e.target.closest("[data-filter]");if(f){filter=f.dataset.filter;redraw();return}let k=e.target.closest("[data-kpi]");if(k){if(k.dataset.kpi==="teams")view="equipes";else{view="circulations";filter=k.dataset.kpi}render();return}let t=e.target.closest("[data-train]");if(t){selected=t.dataset.train;view="circulations";redraw();return}let a=e.target.closest("[data-op]");if(!a)return;let act=a.dataset.op;if(act==="refresh"){a.classList.add("spin");setTimeout(()=>{a.classList.remove("spin");document.querySelector("#syncAge").textContent="0 s";toast("Données opérationnelles synchronisées")},600)}else if(act==="incident")modalOps("Déclarer un incident","Catégorie, gravité et localisation seront transmises au régulateur.");else if(act==="new")modalOps("Nouvelle opération","Planifiez une circulation voyageurs, fret ou maintenance.");else if(act==="fullscreen")document.querySelector(".op-map-card").classList.toggle("expanded");else if(act==="export")toast("Export opérationnel généré avec succès");else if(act==="detail")modalOps("Fiche "+selected,"Composition, équipe, chargement, incidents et chronologie disponibles.");else toast("Action opérationnelle exécutée")});
document.addEventListener("input",e=>{if(e.target.id==="opSearch"){search=e.target.value.toLowerCase();let p=e.target.selectionStart;redraw();let n=document.querySelector("#opSearch");n.focus();n.setSelectionRange(p,p)}});
function modalOps(title,desc){let r=document.querySelector("#modalRoot");r.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><span class="subtle">CENTRE DES OPÉRATIONS</span><h2>${title}</h2></div><button class="icon-btn close-op">×</button></div><div class="modal-body"><p>${desc}</p><div class="form-grid"><div class="field"><label>Type</label><select><option>Circulation ferroviaire</option><option>Incident opérationnel</option><option>Maintenance</option></select></div><div class="field"><label>Priorité</label><select><option>Normale</option><option>Haute</option><option>Critique</option></select></div><div class="field span2"><label>Description</label><textarea rows="4" placeholder="Informations opérationnelles…"></textarea></div></div></div><div class="modal-foot"><button class="btn ghost close-op">Annuler</button><button class="btn primary save-op">Enregistrer et notifier</button></div></div></div>`;r.querySelectorAll(".close-op").forEach(x=>x.onclick=()=>r.innerHTML="");r.querySelector(".save-op").onclick=()=>{r.innerHTML="";toast("Opération enregistrée et équipes notifiées")}}
setInterval(()=>{let c=document.querySelector("#opClock");if(c)c.textContent=new Date().toLocaleTimeString("fr-FR")},1000);
})();
