(function(){'use strict';const css=document.createElement('link');css.rel='stylesheet';css.href='pitch-10min.css';document.head.appendChild(css);
const P=(n,time,axis,title,body)=>`<section class="be-pitch-slide" data-be-pitch="${n}"><div class="be-pitch-meta"><span>${axis}</span><b>SETRAG PILOTAGE</b></div><header><small>${String(n).padStart(2,'0')} / 09</small><h2>${title}</h2></header>${body}</section>`;
const needs=[['Billets difficiles à tracer','Identifiant unique + QR code'],['Réimpressions non maîtrisées','Historique et audit'],['Ventes manuelles','Vente digitale et guichet centralisé'],['Places mal exploitées','Disponibilité par segment'],['Contrôle terrain','Application Contrôleur'],['Faible réseau','Mode hors ligne'],['Écarts financiers','Rapprochement caisse / paiement'],['Reporting manuel','KPI et rapports automatiques'],['Comptabilité','Interface Sage X3'],['Sécurité','SSO, MFA, RBAC et logs']];
const pitch=[
P(1,'30 sec','VISION','Le problème et la vision',`<p class="be-pitch-statement">Transformer une billettique difficile à tracer en une plateforme intégrée, sécurisée et pilotable.</p><div class="be-final-numbers"><span><b>5</b>prestations</span><span><b>1</b>donnée centrale</span><span><b>100 %</b>traçable</span></div><p class="be-pitch-answer">Vente · voyageur · contrôle · finance · décision</p>`),
P(2,'1 min','ASPECT TECHNIQUE','Les besoins SETRAG',`<div class="be-need-grid">${needs.map(x=>`<div><span>${x[0]}</span><i>→</i><b>${x[1]}</b></div>`).join('')}</div>`),
P(3,'2 min','ASPECT TECHNIQUE','Comment fonctionne la solution',`<div class="be-architecture"><div><span>Voyageur</span><span>Guichet</span><span>Contrôleur</span></div><i>↓</i><b>API CENTRALE<small>hors ligne · synchronisation · sécurité</small></b><i>↓</i><strong>BACK OFFICE<small>base centrale · ventes · places · reporting</small></strong><i>↓</i><div><span>Paiements</span><span>Sage X3</span><span>AD</span><span>COLIRAIL</span><span>SIEM</span></div></div>`),
P(4,'1 min','ASPECT TECHNIQUE','Du billet à la comptabilité',`<div class="be-story">${['Le voyageur réserve','La place est bloquée','Le paiement est confirmé','Le billet QR est généré','Le contrôleur scanne','Le contrôle remonte au Back Office','Caisse et reporting mis à jour','Écriture disponible pour Sage X3'].map((x,i)=>`<div><i>${i+1}</i><span>${x}</span></div>`).join('')}</div>`),
P(5,'2 min','ASPECT FINANCIER','Un investissement initial maîtrisé',`<div class="be-pitch-budget"><div class="be-total"><small>INVESTISSEMENT GLOBAL</small><strong>20 000 000</strong><small>FCFA HT</small></div><div><b>10 M</b><span>Back Office</span><em>+</em><b>10 M</b><span>Front Office + Contrôleur</span></div></div><div class="be-mini-allocation">${[['1,2 M','Conception & architecture'],['4,3 M','Développement'],['1,4 M','API & intégrations'],['0,9 M','Cybersécurité / PRA'],['0,9 M','Reporting / analytique'],['1,3 M','Tests / formation / déploiement']].map(x=>`<span><b>${x[0]}</b>${x[1]}</span>`).join('')}</div><div class="be-material-split"><span><b>Matériel de test</b>Pris en charge pendant la réalisation</span><span><b>Parc de production</b>Dimensionné après pilote, sur devis séparé</span></div>`),
P(6,'1 min','ASPECT FINANCIER','Protéger et mieux expliquer les recettes',`<div class="be-levers">${[['Moins de fraude','QR · audit · doublons'],['Moins d’écarts','Caisse · rapprochement'],['Places mieux utilisées','Disponibilité par segment'],['Moins de ressaisie','Reporting · comptabilité'],['Plus de ventes digitales','Web · mobile · agences'],['Recettes visibles','KPI · alertes · traçabilité']].map(x=>`<article><b>${x[0]}</b><span>${x[1]}</span></article>`).join('')}</div><blockquote>L’intérêt financier est aussi de mieux protéger, contrôler et expliquer les recettes existantes.</blockquote>`),
P(7,'1 min','ASPECT COMMERCIAL','Une valeur visible pour toute l’entreprise',`<div class="be-value-four">${[['VOYAGEURS','Achat plus simple','Paiement digital · billet QR · historique'],['EMPLOYÉS','Travail plus rapide','Moins de saisie · outils mobiles'],['DIRECTION','Décision éclairée','KPI · finance · anomalies'],['DSI','Socle maîtrisé','API · sécurité · monitoring']].map(x=>`<article><small>${x[0]}</small><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div>`),
P(8,'1 min','ASPECT COMMERCIAL','Déployer en 6 mois, puis faire évoluer',`<div class="be-six-months">${[['M1','Cadrage'],['M2','Socle'],['M3','Ventes'],['M4','Finance & intégrations'],['M5','Pilotage & sécurité'],['M6','Recette & déploiement']].map(x=>`<span><b>${x[0]}</b>${x[1]}</span>`).join('')}</div><div class="be-pilot-line">Développement <i>→</i> Tests <i>→</i> <b>Pilote terrain</b> <i>→</i> Validation SETRAG <i>→</i> Déploiement</div><div class="be-growth"><b>SOCLE INITIAL</b>${['Nouvelles gares','Nouvelles agences','Nouveaux paiements','Nouveaux tarifs','Nouveaux services','Nouveaux rapports'].map(x=>`<span>${x}</span>`).join('')}</div>`),
P(9,'30 sec','CONCLUSION','Une solution complète, rentable dans son usage et évolutive',`<div class="be-conclusion-three"><article><small>TECHNIQUE</small><b>Une architecture complète</b><p>Qui répond aux besoins métier.</p></article><article><small>FINANCIER</small><b>Un investissement maîtrisé</b><p>Avec des bénéfices mesurables.</p></article><article><small>COMMERCIAL</small><b>Un socle évolutif</b><p>Déployable progressivement.</p></article></div><div class="be-closing-number">20 M FCFA HT <i>·</i> 6 mois <i>·</i> 2 lots <i>·</i> 1 plateforme intégrée</div><p class="be-pitch-statement small">La valeur vient de la connexion entre la vente, le voyageur, le contrôle, la finance, la donnée et la décision.</p>`)
];
const base=pages.business;
pages.business=function(){let h=base();h=h.replace('Budget, calendrier, inclusions et résultat attendu.','Une vision claire du projet, de son financement et de son déploiement.').replace('Mode présentation</button>','Lancer la présentation</button>');const executive=`<section class="be-axis-summary"><article><small>NOTRE SOLUTION</small><b>1. Une réponse technique</b><span>Un système central, simple et sécurisé</span></article><article><small>NOTRE ENGAGEMENT</small><b>2. Un budget maîtrisé</b><span>Chaque investissement produit un résultat concret</span></article><article><small>NOTRE VISION</small><b>3. Une valeur durable</b><span>Un déploiement progressif et évolutif</span></article></section><div class="be-pitch-deck">${pitch.join('')}</div>`;h=h.replace('<nav class="be-jump">',executive+'<nav class="be-jump">').replace('<main class="be-deck">','<div class="be-detail-title"><small>LE PROJET EN DÉTAIL</small><h2>Budget, planning et engagements</h2></div><main class="be-deck">').replace('<span><b data-be-number>1</b> / 18</span>','<span class="be-duration">Présentation SETRAG</span><span><b data-be-number>1</b> / 9</span>');return h};
})();
