(function(){'use strict';
const style=document.createElement('link');style.rel='stylesheet';style.href='presenter-support.css';document.head.appendChild(style);
const glossary=[['API','Un pont qui permet à deux applications de communiquer.','Le site voyageur envoie la réservation au Back Office.'],['Back Office','Le centre de gestion de la plateforme.','Les équipes y gèrent ventes, trains, places, paiements, contrôles et rapports.'],['Front Office','La partie utilisée directement par le voyageur.','Rechercher, réserver, payer et recevoir son billet.'],['SSO','Une seule connexion professionnelle pour accéder aux outils autorisés.','Le compte professionnel SETRAG ouvre les fonctions permises.'],['MFA','Une deuxième vérification de l’identité.','Mot de passe puis code ou validation sur téléphone.'],['RBAC','Chaque personne voit seulement ce qu’elle a le droit de voir.','Un vendeur et un administrateur n’ont pas les mêmes droits.'],['PRA','Le plan pour remettre le système en service après un incident important.','Sauvegardes, procédures et reprise testée.'],['SIEM','L’outil qui rassemble les événements de sécurité et les alertes.','Une activité anormale est signalée à la DSI.'],['Sage X3','Le logiciel comptable avec lequel les données financières sont échangées.','Les ventes sont préparées pour éviter la ressaisie.'],['Yield Management','Mieux gérer les tarifs et les places selon le remplissage et la demande.','La plateforme recommande ; un responsable valide les règles sensibles.'],['Mode hors ligne','Continuer à travailler sans Internet puis envoyer les opérations au retour du réseau.','Le contrôleur peut poursuivre ses contrôles dans une zone mal couverte.'],['QR Code','Un code unique permettant de vérifier rapidement un billet.','Le scan retrouve le statut : valide, utilisé, annulé ou remboursé.'],['Synchronisation','La mise à jour des informations entre les appareils et le système central.','Les contrôles stockés hors ligne remontent quand Internet revient.'],['COLIRAIL','Le système prévu pour le suivi des colis.','Une interface échange les informations utiles sans double saisie.'],['Active Directory','Le système SETRAG qui gère les identités professionnelles.','Un compte désactivé perd automatiquement son accès.']];
const qas=[
['Finance','Pourquoi votre solution coûte 20 millions ?','Le budget couvre deux systèmes complémentaires, les connexions avec le SI SETRAG, la sécurité, les tests, la formation et le déploiement pendant six mois.'],
['Finance','Pourquoi deux lots de 10 millions ?','Le Back Office est le cœur de gestion. Le Front Office et le Contrôleur sont les outils des voyageurs et des agents terrain. Ils communiquent mais répondent à des usages différents.'],
['Déploiement','Pourquoi six mois ?','Il faut comprendre, concevoir, développer, connecter, sécuriser, tester, former puis mettre en production.'],
['Matériel','Pourquoi ne pas acheter tout le matériel immédiatement ?','Le pilote permet de vérifier les équipements sur le terrain avant de choisir les modèles et quantités du parc réel.'],
['Matériel','Qui achète les tablettes ?','Nous prenons en charge le petit matériel de test. Le parc complet de production est acheté par SETRAG ou fourni sur devis séparé.'],
['Technique','Que se passe-t-il sans Internet ?','Le terminal garde temporairement les opérations et les synchronise quand la connexion revient.'],
['Voyageur','Comment empêcher les doubles billets ?','Chaque billet possède un identifiant unique. La place est verrouillée pendant la transaction et chaque contrôle est historisé.'],
['Sécurité','Comment réduire la fraude ?','Avec le QR code, l’identifiant unique, les journaux d’audit et la traçabilité des réimpressions, annulations et remboursements.'],
['Finance','Comment cela augmente-t-il les recettes ?','Nous ne promettons pas un montant arbitraire. La solution réduit les pertes, améliore l’utilisation des places, ouvre des canaux de vente et renforce la maîtrise des encaissements.'],
['Commercial','Comment une place peut-elle être vendue plusieurs fois ?','Jamais sur le même segment. Exemple : place 12, Owendo–Booué pour A, puis Booué–Franceville pour B.'],
['Commercial','Le Yield change-t-il les prix automatiquement ?','Non. Il peut proposer une recommandation. Les règles sensibles restent validées par un responsable autorisé.'],
['Finance','Comment la comptabilité fonctionne-t-elle ?','Les ventes sont consolidées puis préparées dans le format attendu par Sage X3 afin de réduire la ressaisie.'],
['Données','SETRAG garde-t-elle ses données ?','Oui. Elles restent propriété de SETRAG et peuvent être restituées en CSV, JSON ou XML.'],
['Données','Que se passe-t-il si SETRAG change de prestataire ?','La réversibilité prévoit l’export des données et une assistance à la migration d’au moins trois mois.'],
['Déploiement','Qui assure la maintenance ?','Une garantie corrective initiale de six mois est prévue. La suite est dimensionnée selon les besoins.'],
['Finance','Les 20 millions comprennent-ils l’hébergement pour toujours ?','Non. Ils financent la construction. Les coûts futurs dépendent des volumes, de l’infrastructure et du niveau de service choisi.'],
['Commercial','Faut-il repayer pour ajouter une gare ?','Une gare standard est paramétrable sans reconstruire le logiciel. Un besoin particulier peut toutefois nécessiter une évolution.'],
['Sécurité','Pourquoi utiliser Active Directory ?','Pour gérer les accès professionnels avec le système d’identité déjà utilisé par SETRAG.'],
['Voyageur','Pourquoi utiliser le QR code ?','Pour identifier rapidement et de manière unique un billet lors du contrôle.']];
const slideHelp={1:['Nous partons des difficultés actuelles pour construire une plateforme unique.','Parce que la traçabilité relie chaque opération à une personne, une date et un statut.'],2:['Chaque besoin du cahier des charges possède une réponse visible.','La solution a été organisée à partir des problèmes SETRAG, pas à partir d’un logiciel générique.'],3:['Toutes les informations passent par un même système central.','Cela évite les données dispersées et les doubles saisies.'],4:['Une seule vente met à jour le billet, la place, le contrôle, la caisse et la comptabilité.','Les modules partagent la même information au lieu de la recopier.'],5:['Les 20 millions financent deux lots complets sur six mois.','Nous ne vendons pas seulement des écrans : conception, programmation, sécurité, connexions, tests et formation sont inclus.'],6:['Le gain vient aussi de la protection des recettes existantes.','Nous évitons tout ROI fictif et montrons des leviers vérifiables.'],7:['Chaque métier reçoit un bénéfice concret.','Voyageurs, agents, Direction et DSI utilisent la même donnée selon leurs droits.'],8:['Nous testons sur le terrain avant de généraliser.','Le pilote réduit le risque d’acheter un matériel inadapté.'],9:['Deux lots forment une seule plateforme intégrée.','La valeur vient de la connexion entre vente, contrôle, finance et décision.']};
const budget=[['1 200 000 FCFA','Conception & architecture','Comprendre SETRAG, organiser la solution, concevoir les écrans, les règles métier, la sécurité et la migration.','Éviter de développer un outil qui ne correspond pas au terrain.'],['4 300 000 FCFA','Développement','Construire billets, bagages, colis, TAA, funéraire, trains, places, tarifs, finance et administration.','C’est le cœur du logiciel.'],['1 400 000 FCFA','API & intégrations','Connecter paiements, Front Office, Contrôleur, Sage, Active Directory, COLIRAIL et SIEM.','Éviter que les employés ressaisissent les mêmes données.'],['900 000 FCFA','Cybersécurité, monitoring & PRA','Protéger les accès, chiffrer, surveiller, sauvegarder et préparer la reprise.','Les données voyageurs et financières sont sensibles.'],['900 000 FCFA','Reporting & analyse','Créer tableaux de bord, rapports, alertes, analyses de remplissage et de ventes.','Aider la Direction à décider avec des données fiables.'],['1 300 000 FCFA','Tests, formation & déploiement','Tester, corriger, documenter, former, installer et mettre en production.','Un logiciel doit être vérifié et maîtrisé par les équipes.']];
const benefits=[['Voyageur','Temps, simplicité, achat digital et billet sécurisé'],['Vendeur','Moins de saisie, moins de calcul et meilleur historique'],['Contrôleur','Contrôle rapide, mobilité, hors ligne et historique'],['Responsable de gare','Ventes, voyageurs, départs, caisses et équipements visibles'],['Finance','Rapprochement, traçabilité, Sage et explication des écarts'],['Direction','KPI, vision consolidée et meilleure décision'],['DSI','Système central, sécurité, monitoring et contrôle des accès']];
function cards(list,cls=''){return `<div class="ps-cards ${cls}">${list.map(x=>`<article class="ps-searchable"><h3>${x[0]}</h3><p>${x[1]}</p>${x[2]?`<small>${x[2]}</small>`:''}</article>`).join('')}</div>`}
function supportHtml(){const cats=['Tous','Technique','Finance','Commercial','Matériel','Sécurité','Voyageur','Déploiement','Données'];return `<section class="ps-hub" id="ps-summary"><header><small>NIVEAU 2 · SUPPORT DE RÉPONSE</small><h2>Retrouver une réponse pendant les questions</h2><p>Une explication simple, un exemple concret et une réponse prudente.</p></header><div class="ps-search"><span>⌕</span><input data-ps-search placeholder="Rechercher une réponse : coût, API, fraude, tablettes, Sage…"></div>
<details open id="ps-solution"><summary>1. Comprendre la solution <em>En français simple</em></summary><div class="ps-inside"><h3>Comment tout communique</h3><div class="ps-simple-flow"><b>VOYAGEUR<small>achète son billet</small></b><i>↓</i><b>SITE / APPLICATION</b><i>↓</i><strong>SYSTÈME CENTRAL SETRAG<small>ventes · trains · places · paiements · contrôles · rapports</small></strong><i>↓</i><div><span>Contrôleur</span><span>Sage X3</span><span>Paiements</span><span>Sécurité</span></div></div><blockquote>En une phrase : toutes les informations passent par un même système central afin d’éviter les données dispersées.</blockquote><h3>Exemple réel en 30 secondes</h3><div class="ps-amina">${['Amina achète Owendo → Franceville','Elle choisit la place 24','La place est temporairement bloquée','Le paiement est confirmé','Un billet QR unique est créé','Le contrôleur scanne','Le Back Office sait que le billet est utilisé','Caisse, rapports et comptabilité sont mis à jour'].map((x,i)=>`<span><i>${i+1}</i>${x}</span>`).join('')}</div><b class="ps-conclusion">Une seule vente alimente automatiquement plusieurs services.</b></div></details>
<details id="ps-glossary"><summary>2. Les mots techniques expliqués simplement <em>${glossary.length} définitions</em></summary><div class="ps-inside"><div class="ps-glossary">${glossary.map(x=>`<article class="ps-searchable"><h3>${x[0]}</h3><p>${x[1]}</p><small>Exemple SETRAG : ${x[2]}</small></article>`).join('')}</div></div></details>
<details id="ps-budget"><summary>3. Pourquoi 20 millions ? <em>Chaque coût expliqué</em></summary><div class="ps-inside"><blockquote>Nous ne vendons pas seulement des écrans. Le budget couvre conception, programmation, connexions, sécurité, tests, documentation, formation et mise en service.</blockquote><div class="ps-two"><article><b>10 M · Back Office</b><span>Construction du cœur de gestion.</span></article><article><b>10 M · Front Office + Contrôleur</b><span>Outils des voyageurs et des agents terrain.</span></article></div><div class="ps-budget-list">${budget.map(x=>`<details class="ps-searchable"><summary><b>${x[0]}</b> · ${x[1]}</summary><div><h4>Qu’est-ce qu’on paie ?</h4><p>${x[2]}</p><h4>Pourquoi ?</h4><p>${x[3]}</p></div></details>`).join('')}</div></div></details>
<details id="ps-material"><summary>4. Matériel et pilote <em>Qui paie quoi ?</em></summary><div class="ps-inside"><div class="ps-responsibility"><article><small>NOUS · POUR TESTER</small><h3>Notre responsabilité</h3><p>Quelques tablettes, terminal contrôleur, TPE et imprimante de test, lecteurs QR/NFC, cartes test, SIM et accessoires.</p></article><article><small>SETRAG · APRÈS LE PILOTE</small><h3>À dimensionner après validation</h3><p>Parc réel de tablettes, TPE, imprimantes, lecteurs, cartes, bornes, batteries et SIM.</p></article></div><blockquote>Nous testons avant que SETRAG investisse dans un grand parc matériel.</blockquote><h3>Pourquoi un pilote ?</h3><p>Vérifier billet, QR, paiement, impression, hors ligne, synchronisation, batterie et usage par les agents.</p><div class="ps-pilot">TEST <i>↓</i> CORRECTION <i>↓</i> VALIDATION SETRAG <i>↓</i> ACHAT DU PARC RÉEL <i>↓</i> DÉPLOIEMENT</div></div></details>
<details id="ps-value"><summary>5. Qui gagne quoi ? <em>Valeur concrète</em></summary><div class="ps-inside">${cards(benefits,'benefits')}<h3>Trois phrases pour conclure</h3><div class="ps-three-lines"><p><b>Technique</b> Nous réunissons vente, voyageur, contrôle, finance et donnée dans une seule plateforme.</p><p><b>Financier</b> L’investissement construit et sécurise le système tout en protégeant les recettes.</p><p><b>Commercial</b> Le socle évolue vers de nouveaux services sans reconstruire toute la plateforme.</p></div></div></details>
<details id="ps-limits"><summary>6. Limites à connaître <em>Éviter les promesses excessives</em></summary><div class="ps-inside">${cards([['Rails','La plateforme ne remplace pas les rails ni les équipements physiques de signalisation.'],['Recettes','Elle ne garantit pas un montant arbitraire de recettes supplémentaires.'],['Agents','Elle accompagne les agents ; elle ne supprime pas leur rôle.'],['Matériel','Le parc complet de production n’est pas automatiquement inclus.'],['SaaS','Les coûts d’exploitation futurs ne sont pas inclus à vie dans les 20 M.'],['Yield','Les tarifs sensibles ne changent pas sans règles et validation humaine.']],'limits')}</div></details>
<details open id="ps-questions"><summary>7. Questions que le jury peut poser <em>${qas.length} réponses</em></summary><div class="ps-inside"><div class="ps-filters">${cats.map((x,i)=>`<button class="${i?'':'active'}" data-ps-filter="${x}">${x}</button>`).join('')}</div><div class="ps-qas">${qas.map(x=>`<details class="ps-searchable" data-category="${x[0]}"><summary><span>${x[0]}</span>${x[1]}</summary><p>${x[2]}</p></details>`).join('')}</div></div></details>
<details id="ps-memory"><summary>8. Les 10 choses à retenir <em>Imprimable A4</em></summary><div class="ps-inside ps-memory"><button data-ps-print>Imprimer l’aide-mémoire</button>${cards([['1 · 20 M FCFA HT','Investissement initial'],['2 · Deux lots','10 M + 10 M'],['3 · Six mois','Du cadrage au déploiement'],['4 · Back Office','Le cœur de gestion'],['5 · Front Office','L’outil du voyageur'],['6 · Contrôleur','L’outil terrain'],['7 · Hors ligne','Le travail continue sans Internet'],['8 · Tests','Petit matériel pris en charge'],['9 · Production','Parc SETRAG après le pilote'],['10 · Évolution','Un socle conçu pour grandir']],'memory-grid')}</div></details></section>`}
function popup(title,text,more=''){const r=document.querySelector('#modalRoot');if(!r)return;r.innerHTML=`<div class="be-modal"><div><button data-close>×</button><small>EXPLICATION SIMPLE</small><h2>${title}</h2><p>${text}</p>${more}</div></div>`;r.querySelector('[data-close]').onclick=()=>r.innerHTML=''}
function enhance(){const root=document.querySelector('.business-experience');if(!root||root.dataset.presenterReady)return;root.dataset.presenterReady='1';root.classList.add('presenter-help');const top=root.querySelector('.be-top>div:last-child');if(top){const b=document.createElement('button');b.textContent='Masquer l’aide';b.dataset.presenterHelp='';top.prepend(b)}const nav=document.createElement('nav');nav.className='ps-nav';nav.innerHTML=`${[['Résumé','ps-summary'],['Technique','ps-solution'],['Finance','ps-budget'],['Matériel','ps-material'],['Commercial','ps-value'],['Sécurité','ps-limits'],['Questions','ps-questions'],['Conclusion','ps-memory']].map(x=>`<button data-ps-go="${x[1]}">${x[0]}</button>`).join('')}`;root.querySelector('.be-pitch-deck').after(nav);nav.after(document.createRange().createContextualFragment(supportHtml()));root.querySelectorAll('.ps-hub details').forEach(d=>d.open=true);root.querySelectorAll('.be-pitch-slide').forEach(s=>{const n=+s.dataset.bePitch,[say,why]=slideHelp[n];s.insertAdjacentHTML('beforeend',`<aside class="ps-speaker"><b>À dire</b><p>${say}</p><b>Si on vous demande pourquoi</b><p>${why}</p><button data-explain-slide="${n}">Voir plus</button></aside>`)});wire(root)}
function wire(root){root.addEventListener('click',e=>{const help=e.target.closest('[data-presenter-help]');if(help){root.classList.toggle('presenter-help');help.textContent=root.classList.contains('presenter-help')?'Masquer l’aide':'Aide au présentateur'}const exp=e.target.closest('[data-explain-slide]');if(exp){const n=+exp.dataset.explainSlide,[say,why]=slideHelp[n];popup('Slide '+n,say,`<h3>Si le jury demande pourquoi</h3><p>${why}</p>`)}const go=e.target.closest('[data-ps-go]');if(go)document.getElementById(go.dataset.psGo)?.scrollIntoView({behavior:'smooth'});const filter=e.target.closest('[data-ps-filter]');if(filter){root.querySelectorAll('[data-ps-filter]').forEach(b=>b.classList.toggle('active',b===filter));root.querySelectorAll('.ps-qas>details').forEach(q=>q.hidden=filter.dataset.psFilter!=='Tous'&&q.dataset.category!==filter.dataset.psFilter)}const open=e.target.closest('.ps-open');if(open){const s=open.closest('.ps-collapsible');s.classList.toggle('collapsed');open.textContent=s.classList.contains('collapsed')?'Afficher la section':'Replier la section'}if(e.target.closest('[data-ps-print]'))window.print()});const search=root.querySelector('[data-ps-search]');search.oninput=()=>{const q=search.value.trim().toLowerCase();root.querySelectorAll('.ps-searchable').forEach(x=>{x.hidden=q&&!x.textContent.toLowerCase().includes(q)});if(q)root.querySelectorAll('.ps-hub>details').forEach(d=>d.open=true)}}
new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});enhance();
})();
