(function(){
"use strict";
const KEY="setrag_unified_commercial_store_v2",listeners=new Set(),now=()=>new Date().toISOString(),uid=(p,n)=>`${p}-${new Date().toISOString().slice(2,10).replaceAll("-","")}-${String(n).padStart(4,"0")}`;
const seedOperations=[
 {id:"OP-5012",reference:"SET-260802-5012",type:"ticket",customerId:"CL-009821",customer:"Nadia Raponda",passengerId:"PAX-0001",trainId:"EXP-620",coachId:"V2",seatId:"P18",route:"Owendo → Franceville",label:"Billet Express",amount:18000,paymentMethod:"Moov Money",paymentStatus:"confirmé",printStatus:"imprimé",status:"confirmé",agent:"Grâce Mavoungou",createdAt:"2026-08-02T09:40:00",updatedAt:"2026-08-02T09:40:00"},
 {id:"OP-0841",reference:"BAG-260802-0841",type:"baggage",customerId:"CL-009821",customer:"Nadia Raponda",passengerId:"PAX-0001",trainId:"EXP-620",coachId:"Soute V4",route:"Owendo → Franceville",label:"Bagage enregistré · 24 kg",weight:24,amount:3500,paymentMethod:"Lié au billet",paymentStatus:"confirmé",printStatus:"imprimé",status:"enregistré",agent:"Grâce Mavoungou",createdAt:"2026-08-02T09:44:00",updatedAt:"2026-08-02T09:44:00"},
 {id:"OP-0314",reference:"COL-260802-0314",type:"parcel",customerId:"CL-009822",customer:"Louis Nziengui",trainId:"FRET-332",wagonId:"W12",route:"Owendo → Booué",label:"Colis express · 18 kg",weight:18,amount:12400,paymentMethod:"Airtel Money",paymentStatus:"confirmé",printStatus:"imprimé",status:"en transit",agent:"Paul Okoumba",createdAt:"2026-08-02T10:12:00",updatedAt:"2026-08-02T10:12:00"},
 {id:"OP-0029",reference:"TAA-260802-0029",type:"vehicle",customerId:"CL-009823",customer:"Marc Rombi",trainId:"EXP-773",wagonId:"A1",route:"Franceville → Owendo",label:"Véhicule accompagné",amount:85000,paymentMethod:"Carte",paymentStatus:"confirmé",printStatus:"imprimé",status:"confirmé",agent:"Grâce Mavoungou",createdAt:"2026-08-02T10:26:00",updatedAt:"2026-08-02T10:26:00"},
 {id:"OP-0072",reference:"MAR-260802-0072",type:"cargo",customerId:"CLI-IND-04",customer:"Gabon Industrie",trainId:"MIN-642",wagonId:"W08–W12",route:"Moanda → Owendo",label:"Équipements industriels · 48 t",weight:48000,amount:720000,paymentMethod:"Compte client",paymentStatus:"confirmé",printStatus:"imprimé",status:"affecté",agent:"Sarah Agondjo",createdAt:"2026-08-02T11:05:00",updatedAt:"2026-08-02T11:05:00"},
 {id:"OP-5118",reference:"SET-260802-5118",type:"ticket",customerId:"CL-009824",customer:"Alice Lekabi",passengerId:"PAX-0018",trainId:"EXP-620",coachId:"V4",seatId:"P09",route:"Owendo → Booué",label:"Billet Omnibus",amount:12500,paymentMethod:"Espèces",paymentStatus:"en attente",printStatus:"en attente",status:"réservé",agent:"Grâce Mavoungou",createdAt:"2026-08-02T11:18:00",updatedAt:"2026-08-02T11:18:00"}
];
function initial(){return {operations:seedOperations,payments:seedOperations.map((o,i)=>({id:`PAY-${5100+i}`,operationId:o.id,reference:o.reference,method:o.paymentMethod,amount:o.amount,status:o.paymentStatus,createdAt:o.createdAt})),printQueue:seedOperations.map((o,i)=>({id:`PRN-${800+i}`,operationId:o.id,document:o.type==="baggage"?"Étiquette bagage":o.type==="ticket"?"Billet":"Bordereau",reference:o.reference,printer:i%2?"Zebra ZD421":"Epson TM-T88",agent:o.agent,time:o.createdAt.slice(11,16),status:o.printStatus,attempts:1})),cash:{station:"Owendo",desk:"POS-OW-01",register:"CAISSE-01",agent:"Grâce Mavoungou",openedAt:"06:00",openingFloat:150000,theoretical:1845000,declared:1845000,refunds:0,status:"ouverte"},audit:[{id:"AUD-001",action:"OUVERTURE_CAISSE",object:"CAISSE-01",user:"Grâce Mavoungou",at:"2026-08-02T06:00:00",detail:"Fond de caisse 150 000 FCFA"}],sequence:5200};}
let state;try{state=JSON.parse(localStorage.getItem(KEY))||initial()}catch(e){state=initial()}state.operations.forEach(o=>{let p=state.payments.find(x=>x.operationId===o.id);if(p)o.paymentId=p.id});
function persist(){localStorage.setItem(KEY,JSON.stringify(state));listeners.forEach(fn=>fn(state));window.dispatchEvent(new CustomEvent("setrag:store-updated",{detail:state}))}
function audit(action,object,detail){state.audit.unshift({id:`AUD-${Date.now()}`,action,object,user:"Grâce Mavoungou",at:now(),detail})}
function addPayment(op,method,status="confirmé"){let p={id:`PAY-${++state.sequence}`,operationId:op.id,reference:op.reference,method,amount:op.amount,status,createdAt:now()};state.payments.unshift(p);op.paymentId=p.id;return p}
function queuePrint(op,document){let p={id:`PRN-${++state.sequence}`,operationId:op.id,document,reference:op.reference,printer:document.includes("Étiquette")?"Zebra ZD421":"Epson TM-T88",agent:"Grâce Mavoungou",time:new Date().toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"}),status:"en attente",attempts:0};state.printQueue.unshift(p);op.printStatus="en attente";return p}
function base(input,prefix,type,label){let seq=++state.sequence;return {id:`OP-${seq}`,reference:uid(prefix,seq),type,customerId:input.customerId||`CL-${seq}`,customer:input.customer||"Nouveau client",trainId:input.trainId,route:input.route||"Owendo → Franceville",label,amount:+input.amount||0,paymentMethod:input.paymentMethod||"Moov Money",paymentStatus:"confirmé",printStatus:"en attente",status:"confirmé",agent:"Grâce Mavoungou",createdAt:now(),updatedAt:now()}}
function createTicket(input){let op=base(input,"SET","ticket",input.label||"Billet Express");op.passengerId=`PAX-${++state.sequence}`;op.coachId=input.coachId||"V2";op.seatId=input.seatId||`P${state.sequence%40+1}`;state.operations.unshift(op);addPayment(op,op.paymentMethod);queuePrint(op,"Billet voyageur");let parts=op.route.split(" → "),passenger={id:op.passengerId,name:op.customer,ticket:op.reference,train:op.trainId,origin:parts[0],destination:parts[1],car:op.coachId,seat:op.seatId,class:input.class||"Confort",status:"Embarqué",control:"À contrôler",bags:0,assistance:input.assistance||"—"};if(window.SETRAG_OPS){SETRAG_OPS.passengers.unshift(passenger);let t=SETRAG_OPS.trains.find(x=>x.id===op.trainId);if(t){t.quantity++;t.load=`${t.quantity} passagers`}}audit("EMISSION_BILLET",op.reference,`${op.trainId} · ${op.coachId}/${op.seatId} · ${op.amount} FCFA`);persist();return op}
function addBaggage(input){let passenger=window.SETRAG_OPS&&SETRAG_OPS.passengers.find(p=>p.ticket===input.ticket),op=base(input,"BAG","baggage",`Bagage enregistré · ${input.weight||24} kg`);op.passengerId=passenger&&passenger.id;op.weight=+input.weight||24;op.coachId=input.location||"Soute V4";state.operations.unshift(op);addPayment(op,op.paymentMethod);queuePrint(op,"Étiquette bagage");if(passenger){passenger.bags++;SETRAG_OPS.baggages.unshift({id:op.reference,owner:passenger.name,ticket:passenger.ticket,train:passenger.train,type:input.bagType||"Valise",weight:op.weight,origin:passenger.origin,destination:passenger.destination,location:op.coachId,status:"Enregistré",scan:new Date().toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"}),fee:op.amount?`${op.amount.toLocaleString("fr-FR")} FCFA`:"Inclus"})}audit("ENREGISTREMENT_BAGAGE",op.reference,`${op.weight} kg · ${op.coachId}`);persist();return op}
function createFreight(input,type="parcel"){let cargo=type==="cargo",op=base(input,cargo?"MAR":"COL",type,input.label||(cargo?"Marchandises générales":"Colis express"));op.weight=+input.weight||18;op.wagonId=input.wagonId||"W12";op.status=cargo?"affecté":"en transit";state.operations.unshift(op);addPayment(op,op.paymentMethod);queuePrint(op,cargo?"Manifeste marchandises":"Bordereau colis");let t=window.SETRAG_OPS&&SETRAG_OPS.trains.find(x=>x.id===op.trainId);if(t&&cargo){t.quantity+=op.weight/1000;t.load=`${Math.round(t.quantity).toLocaleString("fr-FR")} t`}audit(cargo?"CREATION_MARCHANDISE":"ENREGISTREMENT_COLIS",op.reference,`${op.trainId} · ${op.wagonId}`);persist();return op}
function cancel(id){let op=state.operations.find(x=>x.id===id);if(!op||op.status==="annulé")return;op.status="annulé";op.updatedAt=now();op.printStatus="annulé";let passenger=window.SETRAG_OPS&&SETRAG_OPS.passengers.find(p=>p.ticket===op.reference);if(passenger)passenger.status="Annulé";let t=window.SETRAG_OPS&&SETRAG_OPS.trains.find(x=>x.id===op.trainId);if(t&&op.type==="ticket"){t.quantity=Math.max(0,t.quantity-1);t.load=`${t.quantity} passagers`}refund(id,op.amount,"Annulation du billet");audit("ANNULATION_OPERATION",op.reference,"Place libérée et modules synchronisés");persist()}
function refund(id,amount,reason="Remboursement client"){let original=state.operations.find(x=>x.id===id),op=base({customer:original.customer,customerId:original.customerId,trainId:original.trainId,route:original.route,amount:-Math.abs(amount),paymentMethod:original.paymentMethod},"RMB","refund","Remboursement");op.status="remboursé";op.parentOperationId=id;state.operations.unshift(op);addPayment(op,op.paymentMethod,"remboursé totalement");queuePrint(op,"Avoir / remboursement");state.cash.refunds+=Math.abs(amount);state.cash.theoretical-=Math.abs(amount);audit("REMBOURSEMENT",op.reference,`${reason} · ${amount} FCFA`);persist();return op}
function retryPrint(id){let p=state.printQueue.find(x=>x.id===id);if(p){p.attempts++;p.status="imprimé";let op=state.operations.find(x=>x.id===p.operationId);if(op)op.printStatus="imprimé";audit("REIMPRESSION",p.reference,`Tentative ${p.attempts}`);persist()}}
function hydrateRelations(){if(!window.SETRAG_OPS)return;state.operations.filter(o=>o.type==="ticket"&&o.status!=="annulé").forEach(o=>{if(SETRAG_OPS.passengers.some(p=>p.ticket===o.reference))return;let r=(o.route||"Owendo → Franceville").split(" → ");SETRAG_OPS.passengers.push({id:o.passengerId||`PAX-${o.id}`,name:o.customer,ticket:o.reference,train:o.trainId,origin:r[0],destination:r[1],car:o.coachId||"V2",seat:o.seatId||"P18",class:"Confort",status:"Enregistré",control:"À contrôler",bags:0,assistance:"—"})});state.operations.filter(o=>o.type==="baggage"&&o.status!=="annulé").forEach(o=>{if(SETRAG_OPS.baggages.some(b=>b.id===o.reference))return;let p=SETRAG_OPS.passengers.find(x=>x.id===o.passengerId)||SETRAG_OPS.passengers.find(x=>x.name===o.customer),r=(o.route||"Owendo → Franceville").split(" → ");SETRAG_OPS.baggages.push({id:o.reference,owner:o.customer,ticket:p&&p.ticket||"—",train:o.trainId,type:"Valise",weight:o.weight||0,origin:r[0],destination:r[1],location:o.coachId||"Soute",status:"Enregistré",scan:"Restauré",fee:o.amount?`${o.amount.toLocaleString("fr-FR")} FCFA`:"Inclus"})})}
const api={getState:()=>state,subscribe:fn=>(listeners.add(fn),()=>listeners.delete(fn)),createTicket,addBaggage,createFreight,cancel,refund,retryPrint,persist,audit,reset:()=>{state=initial();persist()}};window.SETRAG_STORE=api;window.operationsStore=api;window.salesStore=api;window.passengerStore={all:()=>window.SETRAG_OPS?.passengers||[]};window.baggageStore={all:()=>window.SETRAG_OPS?.baggages||[]};window.cargoStore={all:()=>state.operations.filter(o=>o.type==="cargo")};window.paymentStore={all:()=>state.payments};window.printQueueStore={all:()=>state.printQueue};window.trainStore={all:()=>window.SETRAG_OPS?.trains||[]};window.auditStore={all:()=>state.audit};hydrateRelations();
})();
